# -*- coding: utf-8 -*-
"""
DRYP: Calculate catchment areas at poin location
"""
import os
import sys
import numpy as np
import pandas as pd
import xarray as xr
#from landlab import RasterModelGrid
#from cuwalid.dryp.components.DRYP_io_files import get_model_settings
from cuwalid.dryp.components.DRYP_io import (
	create_grid_from_extent,# read_raster, save_raster,
	create_landlab_grid,
	get_index_from_coord_file)
from cuwalid.dryp.components.DRYP_flow_accum import runoff_routing
from cuwalid.dryp.components.DRYP_store_functions import (
	save_map_to_rastergrid)
import rasterio
from cuwalid.dryp.components.DRYP_flow_accum import watershed
from cuwalid.tools.DRYP_rrtools import transform_flowdirection_d8_to_landlab_array

def get_flow_path(fname_surface, fname_outlet, fname_out=None,
						fname_flowDir=None, fname_mask=None,
						accum=True, flowdir_format='DRYP'):
	"""Function to create flow path map if the location of the input points
	is provided. This function requires a flow direction map
	but if not provided the flow direction will be created. The function also
	creates a flow accumulation along the path, which is equivalent to the path
	length map.

	Parameters:
	-----------
	fname_surface: str
		file name of the elevation raster map
	fname_outlet : str
		file name of the outflow raster map
	fname_flowdir : str
		(optional) filename of the flow direction raster map
	fname_out : str
		(optional) filename of the output raster file
	fname_mask : str
		(optional) filename of the mask raster file
	accum : bool
		(optional) value that specify if the flow accumulation map is created
	flowdir_format: str
		(optional) value that specify the flow direction format (D8, LDD, GRASS, AGNPS, landlab, DRYP)


	Returns:
	--------
	file
		csv file containing a list areas and node index
		asc flow accumalation map as raster file

		
	Examples:
	---------

	>>> from cuwalid.dryp.components.DRYP_watershed import get_watershed_map
	>>> fname_surface = "surface.asc"
	>>> fname_flowdir = "flowdir.asc"
	>>> fname_outlet = "point.csv"

	>>> get_flow_path(fname_surface, fname_outlet, fname_flowdir)

	"""

	# read datasets: surface, flow direction, and list of points
	surface = read_raster(fname_surface)
	
	# read flow direction
	flowDir = None
	if fname_flowDir is not None:
		if flowdir_format is not "DRYP":
			flowDir = read_raster(fname_flowDir, flatten=False)
			flowDir = transform_flowdirection_d8_to_landlab_array(
			flowDir, format_data=flowdir_format).flatten()
		else:
			flowDir = read_raster(fname_flowDir)
	
	## get raster shape and cellsize
	domain = rasterio.open(fname_surface)
	#grid_shape = (domain.height, domain.width)
	grid_size = (domain.height*domain.width)
	#grid_size = int(domain.nrows*domain.ncols)
	area_cell = np.power(domain.transform[0], 2)

	# read mask
	mask = None
	if fname_mask is not None:
		mask = read_raster(fname_mask)

	# create a raster grid environment, landlab grid
	grid = create_grid_from_extent(
	#grid = create_landlab_grid(
		domain.width,
		domain.height,
		domain.bounds[0],
		domain.bounds[1],
		domain.transform[0], # cell size
		mask)
	
	ro = runoff_routing(grid,
		 	grid_size,
			surface, 
			flowDir,
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			)

	# get basin outlets
	# Output variables and location
	idnodes = get_index_from_coord_file(grid, fname_outlet)[0]

	# create a raster dataset
	unit_area = np.zeros_like(surface)
	
	# create a new raster with the lozation to track
	unit_area[idnodes] = 1.0

	# run runoff component to generate the flow path,
	# the flow path is generated by routing the unit area
	# from the outlet to the catchemnt outlet
	ro.run_runoff_one_step(
						unit_area,# unit area
						np.zeros_like(surface),#AOF
						np.zeros_like(surface),#AOF_threshold,
						np.zeros_like(surface), #conductivity,
						np.ones_like(surface),
						np.zeros_like(surface),# no rivers
						np.full(grid_size, area_cell),
						np.zeros_like(surface),
						np.ones_like(surface)*1e5,
						None)

	# The flow path obtained from the previous step is then used to calculate
	# the flow accumulation map along the flow path
	if accum is True:
		# run runoff component
		ro.run_runoff_one_step(
						ro.discharge,# unit area
						np.zeros_like(surface),#AOF
						np.zeros_like(surface),#AOF_threshold,
						np.zeros_like(surface), #conductivity,
						np.ones_like(surface),
						np.zeros_like(surface),# no rivers
						np.full(grid_size, area_cell),
						np.zeros_like(surface),
						np.ones_like(surface)*1e5,
						None)
	# save files
	if fname_out is None:
		fname_out = fname_surface.split('.')[0]

	# Save contributing area as raster file
	save_map_to_rastergrid(grid, ro.discharge,
			fname_out + '_flowpath.asc')

def get_flow_accumulation(fname_surface, fname_flow_unit_rate=None, fname_out=None,
						fname_flowDir=None, fname_mask=None, field=None, flowdir_format='DRYP'):
	"""This function calculates the flow accumulation map.
	It requires a flow direction map and an the flow unit rate map.
	If the flow unit rate map is not provided, the function will
	create a flow unit rate map.

	This function store all files in the same directory of the
	output files if post processing directory is not provided.
	
	Parameters
	----------
	fname_surface: str
		file name of the elevation raster map
	fname_flow_unit_rate : str
		file name of the flow unit rate raster map
	fname_flowDir : str
		(optional) filename of the flow direction raster map
	fname_mask : str
		(optional) filename of the mask raster file
	fname_out : str
		(optional) filename of the output raster file
	field: str
		(optional) field name of the flow unit rate in case the flow unit rate file is a netcdf file
	flowdir_format: str
		(optional) value that specify the flow direction format (D8, LDD, GRASS, AGNPS, landlab, DRYP)

	Returns
	-------
	file
		asc flow accumalation map as raster file

		
	Examples
	--------

	>>> from cuwalid.dryp.components.DRYP_watershed import get_flow_accumulation
	>>> fname_surface = "surface.asc"
	>>> fname_flow_unit_rate = "flow_unit_rate.asc"
	>>> fname_flowdir = "flowdir.asc"

	>>> get_flow_accumulation(fname_surface, fname_flow_unit_rate, fname_flowdir)
	"""

	# read datasets: surface, flow direction, and list of points
	surface = read_raster(fname_surface)
	
	# read flow direction
	flowDir = None
	if fname_flowDir is not None:
		if flowdir_format is not "DRYP":
			flowDir = read_raster(fname_flowDir, flatten=False)
			flowDir = transform_flowdirection_d8_to_landlab_array(
			flowDir, format_data=flowdir_format).flatten()
		else:
			flowDir = read_raster(fname_flowDir)
	
	## get raster shape and cellsize
	domain = rasterio.open(fname_surface)
	#grid_shape = (domain.height, domain.width)
	grid_size = (domain.height*domain.width)
	#grid_size = int(domain.nrows*domain.ncols)
	area_cell = np.power(domain.transform[0], 2)

	# read mask
	mask = None
	if fname_mask is not None:
		mask = read_raster(fname_mask)

	# create a raster grid environment, landlab grid
	grid = create_grid_from_extent(
	#grid = create_landlab_grid(
		domain.width,
		domain.height,
		domain.bounds[0],
		domain.bounds[1],
		domain.transform[0], # cell size
		mask)
	
	ro = runoff_routing(grid,
		 	grid_size,
			surface, 
			flowDir,
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			)

	# read flow unit rate
	if fname_flow_unit_rate is not None:
		try:
			flow_unit_rate = xr.open_dataset(fname_flow_unit_rate)
			try:
				flow_unit_rate = flow_unit_rate[field].values.flatten()
			except:
				print('Field not found. unit values used instead')
				flow_unit_rate = flow_unit_rate.values.flatten()
			#flow_unit_rate = np.flip(flow_unit_rate, 0)

		except:
			try:
				flow_unit_rate = read_raster(fname_flow_unit_rate)
			except:
				print('Flow unit rate file not found. unit values used instead')
				#flow_unit_rate = read_raster(fname_flow_unit_rate)
				flow_unit_rate = np.ones_like(surface)
	else:
		flow_unit_rate = np.ones_like(surface)

	# runoff component to generate the flow accumulation map
	ro.run_runoff_one_step(
						flow_unit_rate,# unit area
						np.zeros_like(surface),#AOF
						np.zeros_like(surface),#AOF_threshold,
						np.zeros_like(surface), #conductivity,
						np.ones_like(surface),
						np.zeros_like(surface),# no rivers
						np.full(grid_size, area_cell),
						np.zeros_like(surface),
						np.ones_like(surface)*1e5,
						None)
	
	# save files
	if fname_out is None:
		fname_out = fname_surface.split('.')[0]
		fname_out = fname_out + '_var_flowaccum.asc'

	# Save contributing area as raster file
	save_map_to_rastergrid(grid, ro.discharge,
			fname_out)
	

def get_watershed_area(fname_surface, fname_outlet, fname_out=None,
						fname_flowDir=None, fname_mask=None, save_files=True, flowdir_format='DRYP'):
	"""This function calculates the watershed area at a given point location.
	It requires a flow direction map and an outlet point. The function will
	calculate the area and indices (in landlab format). It also
	provides a map of contributing areas (flow accumulation).

	This function store all files in the same directory of the
	output files if post processing directory is not provided.
	
	Parameters
	----------
	fname_surface: str
		file name of the elevation raster map
	fname_outlet : str
		file name of the outflow raster map
	fname_floedir : str
		(optional) filename of the flow direction raster map
	fname_out : str
		(optional) filename of the output raster file
	fname_mask : str
		(optional) filename of the mask raster file
	save_files: bool
		(optional) value that specify if the output files are saved or not
	flowdir_format: str
		(optional) value that specify the flow direction format (D8, LDD, GRASS, AGNPS, landlab, DRYP)


	Returns
	-------
	df: pandas DataFrame
		dataframe containing list of catchment areas and node index
	discharge: numpy array
		array containing the catchment areas at the outlet nodes
	if save_files is True:
		file
			*.csv file containing a list areas and node index
			*.asc flow accumalation map as raster file

		
	Examples
	--------

	>>> from cuwalid.dryp.components.DRYP_watershed import get_watershed_map
	>>> fname_surface = "surface.asc"
	>>> fname_flowdir = "flowdir.asc"
	>>> fname_outlet = "point.csv"

	>>> get_watershed_area(fname_surface, fname_outlet, fname_flowdir)
	"""

	# read datasets: surface, flow direction, and list of points
	surface = read_raster(fname_surface)
	
	# read flow direction
	flowDir = None
	if fname_flowDir is not None:
		if flowdir_format is not "DRYP":
			flowDir = read_raster(fname_flowDir, flatten=False)
			flowDir = transform_flowdirection_d8_to_landlab_array(
			flowDir, format_data=flowdir_format).flatten()
		else:
			flowDir = read_raster(fname_flowDir)
	
	## get raster shape and cellsize
	domain = rasterio.open(fname_surface)
	#grid_shape = (domain.height, domain.width)
	grid_size = (domain.height*domain.width)
	#grid_size = int(domain.nrows*domain.ncols)
	area_cell = np.power(domain.transform[0], 2)

	# read mask
	mask = None
	if fname_mask is not None:
		mask = read_raster(fname_mask)

	# create a raster grid environment, landlab grid
	#grid = create_landlab_grid(
	grid = create_grid_from_extent(
		domain.width,
		domain.height,
		domain.bounds[0],
		domain.bounds[1],
		domain.transform[0], # cell size
		mask)
	#print("grid created", "x:", domain.bounds[1], "y:", domain.bounds[0])
	ro = runoff_routing(grid,
		 	grid_size,
			surface, 
			flowDir,
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			np.zeros_like(surface),
			)

	# get basin outlets
	# Output variables and location
	idnodes = get_index_from_coord_file(grid, fname_outlet)[0]

	ro.run_runoff_one_step(
						np.ones_like(surface),# unit area
						np.zeros_like(surface),#AOF
						np.zeros_like(surface),#AOF_threshold,
						np.zeros_like(surface), #conductivity,
						np.ones_like(surface),
						np.zeros_like(surface),# no rivers
						np.full(grid_size, area_cell),
						np.zeros_like(surface),
						np.ones_like(surface)*1e5,
						None)

	# create dataframe containing list of catchement areas
	df = pd.DataFrame()
	df['IDnode'] = idnodes
	df['Area'] = ro.discharge[idnodes]


	# save files
	if save_files is True:
		if fname_out is None:
			fname_out = fname_surface.split('.')[0]

		# Save contributing area as raster file
		save_map_to_rastergrid(grid, ro.discharge,
				fname_out + '_flowaccum.asc')

		fname = fname_out + '_areas.csv'
		df.to_csv(fname)
	else:
		return df, ro.discharge[idnodes]

def get_watershed_mask(fname_surface, fname_outlet, fname_out=None,
					  fname_flowDir=None, fname_mask=None, raster=False, flowdir_format='DRYP'):
	"""Function to delineate a basin assuming an outlet
	point is provided. This function requires a flow direction map
	but if not provided the flow direction will be created
	
	Parameters
	----------
	fname_surface: str
		file name of the elevation raster map
	fname_outlet : str
		file name of the outflow raster map
	fname_flowDir : str
		(optional) filename of the flow direction raster map
	fname_out : str
		(optional) filename of the output raster file
	raster: bool
		value that specify if it is a raster or csv fname_outlet
	fname_mask : str
		(optional) filename of the mask raster file
	flowdir_format: str
		(optional) value that specify the flow direction format (D8, LDD, GRASS, AGNPS, landlab, DRYP)

	Returns
	-------
	raster file


	Examples
	--------
	>>> from cuwalid.dryp.components.DRYP_watershed import get_watershed_map
	>>> fname_surface = "surface.asc"
	>>> fname_flowdir = "flowdir.asc"
	>>> fname_outlet = "point.csv"
	>>> get_watershed_mask(fname_surface, fname_outlet, fname_flowdir)
	"""

	# read datasets: surface, flow direction, and list of points
	surface = read_raster(fname_surface)
	
	# read flow direction
	flowDir = None	
	if fname_flowDir is not None:
		if flowdir_format is not "DRYP":
			flowDir = read_raster(fname_flowDir, flatten=False)
			flowDir = transform_flowdirection_d8_to_landlab_array(
			flowDir, format_data=flowdir_format).flatten()
		else:
			flowDir = read_raster(fname_flowDir)
	
	# read mask
	mask = None
	if fname_mask is not None:
		mask = read_raster(fname_mask)

	## get raster shape and cellsize
	domain = rasterio.open(fname_surface)
	grid_shape = (domain.height, domain.width)
	#grid_size = int(domain.nrows*domain.ncols)
	#area_cell = np.power(domain.transform[0], 2)

	# create a raster grid environment, landlab grid
	#grid = create_landlab_grid(
	grid = create_grid_from_extent(
		domain.width,
		domain.height,
		domain.bounds[0],
		domain.bounds[1],
		domain.transform[0], # cell size
		mask)
	
	# initializa watershed module
	basin = watershed(grid, surface, flowDir)

	# get basin outlets
	if raster is True:
		outlet = read_raster(fname_outlet)
	else:	
		# Output variables and location
		idnodes = get_index_from_coord_file(grid, fname_outlet)[0]

		# create array with outlets
		outlet = np.zeros_like(surface)
		outlet[idnodes] = 1

	# get watershed
	basinmask = basin.get_watersheds(outlet)

	# reshape landlab grid into a 2D numpy array
	basinmask = np.flip(basinmask.reshape(grid_shape), 0)
	
	# get raster file properties
	surface, profile, transform = open_raster(fname_surface)

	# save files
	if fname_out is None:
		fname_out = fname_surface.split('.')[0] + '_basin.asc'

	# save raster dataset
	save_raster(fname_out, basinmask, profile, transform)

def open_raster(fname):
	with rasterio.open(fname) as src:
		# Read the input raster data
		data = src.read(1)
		# Get the metadata of the input raster
		profile = src.profile
		# Get the affine transformation
		transform = src.transform
	return data, profile, transform

def get_raster_properties(fname):
	domain = rasterio.open(fname)
	grid_ncols = domain.width
	grid_nrows = domain.height
	#grid_xllcorner = domain.bounds[1]
	#grid_yllcorner = domain.bounds[0]
	grid_cellsize = domain.transform[0]
	return grid_ncols, grid_nrows, grid_cellsize

def read_raster(fname, flatten=True):
	data = np.flip(rasterio.open(fname).read(1), 0)
	if flatten:
		data = data.flatten()
	return data

def save_raster(fname, data, profile, transform):
	os.remove(fname) if os.path.exists(fname) else None
	with rasterio.open(fname, 'w', **profile) as dst:
		# Write the modified raster data
		dst.write(np.array(data, dtype=np.float32), 1)
		# Set the affine transformation
		dst.transform = transform