import os
import glob
import subprocess

# Define the directory where your .rst files are located
docs_source_dir = 'source/'
docs_dir = '.'  # Directory containing the Makefile
module_dir = '../cuwalid'

# Define the marker string that identifies autogenerated files
autogenerated_marker = '.. automodule::'

# Function to delete autogenerated .rst files
def delete_autogenerated_rst_files(directory, marker):
    for rst_file in glob.glob(os.path.join(directory, '*.rst')):
        with open(rst_file, 'r') as file:
            content = file.read()
            if marker in content:
                os.remove(rst_file)
                print(f"Deleted autogenerated file: {rst_file}")

# Clean the directory by deleting autogenerated .rst files
delete_autogenerated_rst_files(docs_source_dir, autogenerated_marker)

# Run sphinx-apidoc with the force option to overwrite any remaining conflicting files
subprocess.run(['sphinx-apidoc', '-f', '-o', docs_source_dir, module_dir])

# Run 'make clean' to clean the build directory
subprocess.run(['make', 'clean'], cwd=docs_dir)

# Build the documentation
subprocess.run(['make', 'html'], cwd=docs_dir)
